name: Publish VS Code Extension to OpenVSX Marketplace

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # https://github.com/marketplace/actions/setup-node-js-environment
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install ovsx
        run: npm install -g ovsx

      - name: Run tests
        run: npm run test:unit

      # https://github.com/marketplace/actions/manual-workflow-approval
      - uses: trstringer/manual-approval@74d99dff7380e3e4b122d4ededcbca2b6ce59367 # v1.12.0
        with:
          secret: ${{ github.TOKEN }}
          approvers: fcarnicero,nanoalbelda,vdlr
          minimum-approvals: 1
          timeout-minutes: 5    
      
      - name: Publish to Open VSX
        if: success()
        run: ovsx publish
        env:
          OVSX_PAT: ${{ secrets.OPEN_VSX_TOKEN }}
      