name: Publish VS Code Extension to Marketplace

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install vsce
        run: npm install @vscode/vsce

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:unit

      - name: Package extension
        run: npx vsce package --allow-missing-repository

      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: xygeni-scanner-vscode
          path: "*.vsix"

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: fcarnicero,nanoalbelda,vdlr
          minimum-approvals: 1
          timeout-minutes: 5    

      - name: Publish extension to Marketplace
        if: success()
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx vsce publish --pat $VSCE_PAT