name: Publish Xygeni Scanner VS Code Extension

on:
  push:
    tags:
      - 'v*.*.*' # Trigger only on version tags like v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install vsce
        run: npm install @vscode/vsce

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:unit

      - name: Package extension
        run: vsce package

      - name: Publish Xygeni Scanner to Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: vsce publish --pat $VSCE_PAT